### ISSUE TITLE
How to contribute to the project?

### ISSUE THREAD

**Issue by Ismailco** [ahangarha/MV-Projects#19]
Hi, It will be nice if you can explain how to contribute to this project.

**Comment by ahangarha** [comment]
Hi. Thank you for asking this question.

Contribution to this project is very much like contributing to any other Free/Libre and Open Source project. Just follow these steps:

1. Fork this repo (because you don't have access to push to this repo, you need to have a copy of that on your account)
2. Clone your fork on your system
3. Make a new branch from `develop` branch (this is important here! you need to checkout to `develop` branch and then make a branch)
4. Make the local development environment ready by running `npm install`.
5. To run the project on live server, run `npm run watch`.
6. Commit your changes.
7. Push your commits to your own fork
8. Send Pull Request from your new branch to this project's **develop branch**.

You are done. I will get notified and then take the next steps accordingly.

If later you need to contribute, you need to first make sure your fork is up to date. You should see a button on your fork for synchronization. After that, you need to use `git pull` on your clone (on you local machine) to get latest commits and then the rest is the same...

Notice: live demo wont work on your own repo. For that, we need to have a proper deploy script. We don't have that now. I so some trick to get it work on my repo.

**Comment by ahangarha** [comment]
## Update:
I just migrated the project to use webpack and now with the help of deploy script, live demo works on gh-pages.
